#配置端口号
server:
  port: 8001

#配置mybatis
mybatis:
  type-aliases-package: com.aaa.springcloud.entity
  mapper-locations: mapper/*.xml

#配置Spring
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/yhsktest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root