#配置端口号
server:
  port: 9001

#配置mybatis
mybatis:
  type-aliases-package: com.aaa.springcloud.entity
  mapper-locations: mapper/*.xml

#配置Spring
spring:
  application:
    name: springcloud-tigong-ip  #在注册中心显示
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/yhsktest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root


#Eureka配置，将提供者注册进服务器
eureka:
  client:
    #服务端地址
    service-url:
      #defaultZone: http://localhost:7001/ #单机模式下注册进服务端

      #集群模式下注册进三个服务器  路径要有eureka，不然注册不进去
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #修改默认的描述信息
    instance-id: ${server.port}-hystrix
    #prefer-ip-address: true  #改为true后默认显示的是ip地址而不再是localhost


#Eureka的详细信息，可以添加key-value样式提示微服务的构建者
info:
  app.name: Tujiji~Hystrix熔断
  company.name: com.aaa.springcloud

